---
- name: Delete Block list entry
  hosts: checkpoint
#  become: true
  tasks:
    - name: Ensure UFW is installed
      apt:
        name: ufw
        state: present

    - name: Add rule to deny specific IP address
      ufw:
        rule: deny
        from: 192.168.56.112

    - name: Delete firewall rule
      command: ufw delete deny from 192.168.56.112

    - name: Restart UFW firewall
      service:
        name: ufw
        state: restarted
        enabled: yes
